### ISSUE TITLE
Feature Request: Outlet Device Type

### ISSUE THREAD

**Issue by luciengaitskell** [webdeck/homebridge-indigo#11]
The README says that Indigo Outlets are shown as lights. As HomeKit and Homebridge allow this service, it would be nice if it could be implemented here. This would prevent devices on the outlet switch from being turned off from a "turn all the lights off" command to Siri.

**Comment by webdeck** [comment]
You can use the treatAsSwitchIds setting to have the outlets treated as switches, which means they will not be turned on or off when you tell Siri to turn the lights on or off.
