### ISSUE TITLE
[enhancement] Support Motion Detectors

### ISSUE THREAD

**Issue by kcjonson** [webdeck/homebridge-indigo#14]
Simple feature request to support motion detectors.

This may be something I could tackle myself if you would be open to a PR.  Was there anything particular I should think about when diving into this? They seem to have a very simple API, so I'm hoping that its straightforward.

**Comment by kcjonson** [comment]
As per #7 , this one is blocked until we can get update events coming reliably from Indigo.

**Comment by webdeck** [comment]
Added in #15
