### ISSUE TITLE
[question] can motion sensors trigger iOS notifications?

### ISSUE THREAD

**Issue by blysik** [webdeck/homebridge-indigo#17]
Hi,

I successfully setup a motion sensor from indigo into homebridge.  Next, I configured the motion sensor in the Home app to send a notification.   However, triggering this motion sensor never sets off an iOS notification like I expect.

Is this working as expected?

**Comment by webdeck** [comment]
Once the Homebridge Buddy Indigo plugin is updated so that it notifies homebridge-indigo whenever a device state changes, then it should work.  It doesn't work without the Indigo plugin as well.

**Comment by Colorado4Wheeler** [comment]
I had considered that but the callback should be in place already.  Maybe it's not working on sensors.  I haven't changed anything since our last discussions on that callback because it was sort of beta, is it still the same?

**Comment by webdeck** [comment]
Callbacks have been fully implemented for all the device types.  I don't have any motion sensors to test with, so if you can paste the log file in, that would help debug.

**Comment by Colorado4Wheeler** [comment]
Ok, so that test setup is totally implemented, I'll make sure it propagates down in the next update.
