### ISSUE TITLE
Status update from Homekit

### ISSUE THREAD

**Issue by KardelSniper** [webdeck/homebridge-indigo#19]
Just wondering, will this plugin notify Indigo of device state changes made from HomeKit? From my usage this doesn't seem to be happening, so that say if I turn on/off a light using HomeKit, Indigo will not update the device status accordingly. Please advise. Thanks!

**Comment by webdeck** [comment]
I don't see how that is possible, as the way this plugin updates the state of an Indigo-controlled device is to use Indigo's API to tell Indigo to update the device, so Indigo knows the correct state of the device.

Are you trying to get Indigo to know the state of a Homekit-only device?  If so, that's not what this plugin does.

**Comment by KardelSniper** [comment]
Hi thanks for the quick reply! I'm not sure I understand what you mean, so my situation is: I'm using Indigo and Homebridge to replace my Insteon Hub Pro. And I found when I operate my Insteon devices from HomeKit, the device state is not updated in Indigo, so that I have to run a schedule to iterate through all devices to update their states. I was hoping if when HomeKit operates a device, this plugin can somehow notify Indigo of the device state change, that'll be perfect. I guess the missing part is to get this status change from HomeKit? Are you saying this is not possible to realize? Please advise. Thanks a lot!!

**Comment by webdeck** [comment]
This plugin plus Indigo would replace the Insteon Hub Pro and would keep Indigo's state updated correctly.  If you use the Insteon Hub Pro and Indigo at the same time, state gets confused because Insteon devices can only link to one hub - they can't link to both Indigo and the Insteon Hub.

**Comment by KardelSniper** [comment]
Thanks for the reply! I think now I get what you're saying. I haven't removed the Hub Pro yet so I might be operating my Insteon through the old HomeKit devices that belong to the Hub Pro. I'll try to remove the Hub Pro and operate through HomeBridge and see if the device states update correctly. Will report back when I get it done. Thank you again! Very much appreciated!

**Comment by KardelSniper** [comment]
Turns out it is exactly as you said. I removed the Insteon Hub Pro and use Indigo exclusively, now everything works like a charm! Thanks for the help!
