### ISSUE TITLE
HVAC mode not working

### ISSUE THREAD

**Issue by jsmith79** [webdeck/homebridge-indigo#20]
Hi Guys,

I am having an issue with controlling the mode of my thermostat from homekit.
If i change the temp from homekit indigo changes the temp but when i try to turn on or off indigo does not change anything.
After looking on the [wiki](http://wiki.indigodomo.com/doku.php?id=indigo_s_restful_urls) i started playing with a few things, on line 1566 of index.js i changed ` qs = { hvacOperationModeIsOff: "true" }; ` to `qs = { hvacCurrentMode: "all off"};` and i can now turn the hvac system off from home kit.
I also changed the next few lines to "cool on", "heat on" and "auto on" and those modes now work, is this ok to change these lines? should it be working without any mods at the moment?
I am pretty new to all this and just want to make sure i don't break anything.

**Comment by dgburtonbv** [comment]
I had the same issue!

**Comment by webdeck** [comment]
Clearly, I didn't test this well enough.  I will fix it shortly.

**Comment by webdeck** [comment]
I have published a new version to npm that includes this fix.  Thanks for reporting this!
