### ISSUE TITLE
Setting Power State to "On" always bumps brightness to 100%

### ISSUE THREAD

**Issue by brendanjerwin** [webdeck/homebridge-indigo#5]
I don't think that's quite right. When configuring a scene, if I set the power state on and set the brightness (say to 10%) then the lights pulse on to 100% then back down or, sometimes depending on how the timing works out, they will dim to 10% _first_ and end up at 100%.

The workaround is to not configure the power state in the scene but I have to imagine this is causing more subtle problems elsewhere.

**Comment by webdeck** [comment]
Setting power state to on tells indigo to turn the device on.  You can adjust brightness without touching power state if that is what you want to accomplish.
