### ISSUE TITLE
treatAsFanID - new config config?

### ISSUE THREAD

**Issue by dgburtonbv** [webdeck/homebridge-indigo#6]
Thanks for your work on this!

Is it possible to add in another config option - "treatAsFanID" - which would take an Indigo on/off device (i.e. a Z-wave relay) and represent it as a single-speed fan in Homekit?

**Comment by brendanjerwin** [comment]
@dgburton it is possible to, in HomeKit, mark a switch as a fan. 

Using http://selfcoded.com/home/ In the Services tab you can change what class it is associated with. Once that's done Siri understands "turn on the fan in X room". I imagine other HomeKit apps can as well.

Edit - Yeah, in iOS Home you can change the "Type" as well in the Details of the device.

**Comment by dgburtonbv** [comment]
Got it. Thanks @brendanjerwin
