### ISSUE TITLE
Feature Request - Default Device Type to Switch

### ISSUE THREAD

**Issue by brendanjerwin** [webdeck/homebridge-indigo#8]
I'd like to be able to update my config once to change the default device type from a light to a switch. At least for simple on/off devices. This would let me specify within HomeKit what kind of device it is. As it is I keep needing to go into the config and mark a new device as a switch...

Thoughts? Any direction on implementation?

**Comment by webdeck** [comment]
That would add a more configuration complexity (as you would then need a "treatAsLight" option) without adding any additional functionality.  I don't think it is worth the complexity it causes.
